### ISSUE TITLE
why db storage '#' symbol?

### ISSUE THREAD

**Issue by mrgaolei** [charettes/django-colorful#30]
I found that in db django-colorful storage '#ff0000' with varchar(7).
But why using archer(6) and storage 'ff0000'?

**Comment by charettes** [comment]
I assumed you meant `varchar(6)` and not archer.

This format was chosen to be based on the W3C spec instead.

If you're asking in term of optimal storage performance note that most database store `varchar(n)` using the same way for most value of `n` which only results in a database constraint. If we really wanted to save storage we should use some kind of binary or integer field in the first place.

**Comment by mrgaolei** [comment]
Or use `char(6)` to instead of `varcher(7)`?
Because I want use ColorField to be primary_key and for many ForeignKey.

**Comment by charettes** [comment]
Django's CharField use `varchar` internally and can be used as primary keys and be referenced by ManyToField fieds. I'm not sure I understand what you mean here.
