### ISSUE TITLE
color palet shows behind bootstrap model

### ISSUE THREAD

**Issue by gabn88** [charettes/django-colorful#31]
If you see the css, 

div.colorPicker-palette {
    width: 110px;
    position: absolute;
    border: 1px solid #598FEF;
    background-color: #EFEFEF;
    padding: 2px;
    z-index: 9999;
}

However, in browsers that don't support native html5 color input the palette shows like:
`<div id="color_selector" style="left: 975px; top: 209.7px; display: block; z-index: 1050;"><div style="background-color: rgb(153, 204, 255);">&nbsp;</div><div class="color_swatch" style="background-color: rgb(255, 255, 255);">&nbsp;</div><div id="color_custom"><label for="color_value">Hex</label><input id="color_value" type="text" size="8"></div></div>`

So I think the css class should be:

#color_selector instead of div.colorPicker-palette?

**Comment by charettes** [comment]
I'm not sure how the `<div id="color_selector">` was generated but it doesn't look like it was from this project. I've no idea what you mean by Boostrap model?

**Comment by gabn88** [comment]
Wow, this is strange!

If I use the latest version from github I have a totally different django-colorful then when I use the latest version from PiPy! Also they seem to be incompatible (colorfield needs to be iterable error)
