### ISSUE TITLE
Django version restrictions

### ISSUE THREAD

**Issue by snig-b** [charettes/django-colorful#37]
Is there any version that is compatible with Django 1.6.5? The installation automatically upgrades/installs Django 1.9 , which is not compatible with my project code.
May I know if there are a number of Django 1.8 code usages in the project, or simply downgrading the version would work in a fork?

**Comment by charettes** [comment]
Django 1.6 and 1.7 are deprecated, you should update you Django version.

`django-colorful==1.0.1` was the latest version to support Django 1.6.
