### ISSUE TITLE
Do not show "other", in order to use only a subset of defined colors

### ISSUE THREAD

**Issue by erwinfeser** [charettes/django-colorful#38]
It would be great to have that feature

**Comment by charettes** [comment]
I'm not sure I get what you mean. Patches are welcome.

**Comment by marcosguedes** [comment]
I guess his problem is the same as mine, to forbid users to select a custom color instead the ones predefined in colors=[]

![image](https://cloud.githubusercontent.com/assets/6418368/20965529/efcecece-bc6d-11e6-9a4d-6506ac4860c3.png)

**Comment by charettes** [comment]
@marcosguedes makes sense. Could you come you come up with a patch?

**Comment by alex-ong** [comment]
This was closed; but was there any inkling of help for a workaround?
