### ISSUE TITLE
INSTALLED_APPS.append('colorful') not working

### ISSUE THREAD

**Issue by Florvis** [charettes/django-colorful#44]
Hi, 
I'm quite new to python (so also Django) and web servers.
But I followed the Django tutorial https://docs.djangoproject.com/en/1.11/intro/tutorial01/
So now I'm able to acces a web  page.
I want to have a color picker on my page, but while trying, I don't get where or how I should use the INSTALLED_APPS.append('colorful'). If I add manualy 'colorful' in the INSTALLED_APPS list, I get an error too.

Any feedback would be welcome! 
Thanks in advance
Floris

**Comment by charettes** [comment]
Hi @Florvis, you must add `'colorful'` to the `INSTALLED_APPS` list in your `settings.py` file.

What's the error you are receiving? Did you make sure to install the package using `pip install django-colorful`?

**Comment by Florvis** [comment]
Hey, 

Below you can find a screenshot of the error, and one of the settings.py file.
I'm sure I did the pip install.

![image](https://user-images.githubusercontent.com/6705665/30711910-828a6c94-9f0a-11e7-9876-8c52582dd3de.png)

![image](https://user-images.githubusercontent.com/6705665/30711960-a4094070-9f0a-11e7-95e5-e49e5517c7d1.png)

**Comment by charettes** [comment]
Hey Floris,

I'm sorry but the error you're encountering as little to do with `django-colorful` so I'm going to close this ticket. I suggest you try to get support for Django (I think you are going through the tutorial judging from the `Poll` model name) through the mailing list or on IRC. You can find link to these ressources from the documentation.

Best,
Simon
