### ISSUE TITLE
Django 2.1 stopped supporting widgets without explicit renderer arg definition

### ISSUE THREAD

**Issue by MarianoFontana** [charettes/django-colorful#47]
As we can see in the release notes for Django 2.1 (https://docs.djangoproject.com/en/2.1/releases/2.1/):
> Support for Widget.render() methods without the renderer argument is removed.

As the ColorFieldWidget render method does not have a `renderer` kwarg, it fails when rendering:
```python
def render(self, name, value, attrs={}):
```
It should be enough to just add:
```python
def render(self, name, value, attrs={}, **kwargs):
```

**Comment by charettes** [comment]
Fixed in b4fc970b18fce549083f118e604f92820dd4fb94, a version with the commit should be released early next week.
