### ISSUE TITLE
django-colorful 1.3 on PyPI

### ISSUE THREAD

**Issue by matthiask** [charettes/django-colorful#48]
Hey,

It seems that 1.3 isn't available on PyPI yet: https://pypi.org/project/django-colorful/#history

Would be great if you got around to uploading the release. Thanks in advance!

**Comment by charettes** [comment]
I just released 1.3 https://pypi.org/project/django-colorful/#history

Sorry for the wait, I encrypted my Pypi credentials so this doesn't happen in the future.

69d73bf60cf791f006e3a32bc7fee2cd322de8d9

Enjoy!

**Comment by matthiask** [comment]
Thanks!!
